autograd_mode: vmap
benchmarking_costs: false

outer_optim:
  num_epochs: 2
  batch_size: 128
  lr: 1e-4
  device: 0

inner_optim:
  error_function: homography_error_fn
  max_iters: 50
  step_size: 0.1

defaults:
  - model: simple_cnn

hydra:
  run:
    dir: examples/outputs/homography_estimation
  job_logging:
    handlers:
      file:
        filename: my_log_output.log

dataset:
  name: x
  path: /home/mackop/Github/gps-denied-uav-localization/sat_data/woodbridge/images
  viz_every : 50
  save_every: 150
  num_workers: 4
  val_workers: 1
  imgH: 60
  imgW: 80
  num_samples: 1000

parameter_ranges:
  lower_sz: 80
  upper_sz: 100
  warp_pad: 0.4
  min_scale: 1.00
  max_scale: 1.00
  angle_range: 15
  projective_range: 0
  translation_range: 10
